feat(navbar): added nav bar comopnent
Underdog-Devs/website pull request #57
Opened 2020-12-28 21:35 UTC by JessBonanno

# Description
Fixes # (issue #49  from issue tracker)

- We styled this to be responsive to match the spec. 
- We needed to install the ant design icons package for the mobile menu button.

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status
- [ ] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?
- [ ] Unit Tests
- [ ] Integration Tests
- [ ] User Tests

# Checklist
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

2021-01-04 08:26 UTC, jlong5795 requested changes

2021-01-04 08:26 UTC, jlong5795 commented on src/App.js
> +      {/*<header className="App-header">*/}
Generally against commented out code in prod. This appears to be boilerplate that can be removed. I suggest removal.

2021-01-12 23:27 UTC, matthewweale approved these changes

2021-01-12 23:28 UTC, matthewweale approved these changes

2021-01-12 23:28 UTC, matthewweale approved these changes

2021-01-12 23:47 UTC, SYGINT approved these changes

2021-01-12 23:51 UTC, merged